# Generated by Django 5.0.3 on 2024-03-24 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0003_alter_author_created_by_alter_quote_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quote",
            old_name="quote",
            new_name="name",
        ),
    ]
